server:
  port: 8182

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
    appName: eureka-server
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    dashboard:
      enabled: true
      path: /

management:
  endpoint:
    heapdump:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, env, heapdump, metrics

info:
  app:
    name: ${spring.application.name}
    version: @project.version@